language: go
sudo: required
go:
  - "1.11.2"
  - master

env:
  - KAFKATAG=kafkav1
  - KAFKATAG=kafkav2

notifications:
  email: false

before_install:
    - go get -tags $(KAFKATAG) -t -v ./...
script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -tags $(KAFKATAG) -v ./... -timeout 1m
  - make build
