language: go
sudo: required
go:
  - 1.8
  - tip

notifications:
  email: false

before_install:
    - go get -t -v ./...
script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -v ./... -timeout 1m
  - make build
