language: go
sudo: required
go:
  - "1.11.2"
  - master

notifications:
  email: false

before_install:
    - go get -tags kafkav1 -t -v ./...
script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -tags kafkav1 -v ./... -timeout 1m
  - make build
